###############################################################################
# Evaluating the Impact and Cost-Effectiveness of Typhoid Conjugate Vaccine 
#   Schedules across Diverse Settings: a Multi-Model Comparison
# 
# Code to load the output from the transmission dynamic model
#
# Created: Catherine Wenger Jan 2025
###############################################################################

load_cases_by_year <- function(){
## MEDIUM Incidence
## Slow waning 
load(here("Process_TDM_output","Output","9moW","Scenario_MediumA_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_MediumB_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_MediumC_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moWO","Scenario_MediumD_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moW","Scenario_MediumE_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_MediumF_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_MediumG_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_MediumH_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_MediumI_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_MediumJ_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_MediumK_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moWO","Scenario_MediumL_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moW","Scenario_MediumM_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_MediumN_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_MediumO_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moWO","Scenario_MediumP_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moW","Scenario_MediumQ_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
## Fast waning 
load(here("Process_TDM_output","Output","9moWO","Scenario_MediumB_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_MediumC_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moWO","Scenario_MediumD_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moW","Scenario_MediumE_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_MediumF_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_MediumG_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_MediumH_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_MediumI_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_MediumJ_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_MediumK_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moWO","Scenario_MediumL_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moW","Scenario_MediumM_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_MediumN_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_MediumO_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moWO","Scenario_MediumP_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moW","Scenario_MediumQ_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)


## HIGH INCIDENCE
## Slow waning 
load(here("Process_TDM_output","Output","9moW","Scenario_HighA_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_HighB_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_HighC_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moWO","Scenario_HighD_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moW","Scenario_HighE_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_HighF_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_HighG_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_HighH_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_HighI_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_HighJ_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_HighK_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moWO","Scenario_HighL_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moW","Scenario_HighM_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_HighN_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_HighO_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moWO","Scenario_HighP_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moW","Scenario_HighQ_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
## Fast waning 
load(here("Process_TDM_output","Output","9moWO","Scenario_HighB_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_HighC_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moWO","Scenario_HighD_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moW","Scenario_HighE_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_HighF_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_HighG_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_HighH_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_HighI_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_HighJ_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_HighK_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moWO","Scenario_HighL_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moW","Scenario_HighM_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_HighN_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_HighO_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moWO","Scenario_HighP_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moW","Scenario_HighQ_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)

## VERY HIGH INCIDENCE
## Slow waning 
load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighA_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighB_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighC_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moWO","Scenario_VeryHighD_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moW","Scenario_VeryHighE_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighF_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighG_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighH_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighI_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighJ_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighK_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moWO","Scenario_VeryHighL_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moW","Scenario_VeryHighM_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighN_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighO_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moWO","Scenario_VeryHighP_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moW","Scenario_VeryHighQ_Slow_Cases_per_year.Rdata"), envir = .GlobalEnv)
## Fast waning 
load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighB_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighC_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moWO","Scenario_VeryHighD_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moW","Scenario_VeryHighE_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighF_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighG_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighH_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighI_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighJ_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighK_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moWO","Scenario_VeryHighL_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moW","Scenario_VeryHighM_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighN_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighO_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moWO","Scenario_VeryHighP_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
load(here("Process_TDM_output","Output","15moW","Scenario_VeryHighQ_Fast_Cases_per_year.Rdata"), envir = .GlobalEnv)
}

load_doses_by_year <- function(){
  ## MEDIUM INCIDENCE
  ## Slow waning 
  load(here("Process_TDM_output","Output","9moWO","Scenario_MediumB_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_MediumC_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moWO","Scenario_MediumD_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moW","Scenario_MediumE_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_MediumF_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_MediumG_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_MediumH_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_MediumI_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_MediumJ_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_MediumK_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moWO","Scenario_MediumL_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moW","Scenario_MediumM_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_MediumN_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_MediumO_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moWO","Scenario_MediumP_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moW","Scenario_MediumQ_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  ## Fast waning 
  load(here("Process_TDM_output","Output","9moWO","Scenario_MediumB_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_MediumC_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moWO","Scenario_MediumD_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moW","Scenario_MediumE_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_MediumF_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_MediumG_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_MediumH_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_MediumI_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_MediumJ_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_MediumK_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moWO","Scenario_MediumL_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moW","Scenario_MediumM_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_MediumN_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_MediumO_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moWO","Scenario_MediumP_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moW","Scenario_MediumQ_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  
  ## HIGH INCIDENCE
  ## Slow waning 
  load(here("Process_TDM_output","Output","9moWO","Scenario_HighB_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_HighC_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moWO","Scenario_HighD_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moW","Scenario_HighE_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_HighF_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_HighG_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_HighH_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_HighI_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_HighJ_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_HighK_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moWO","Scenario_HighL_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moW","Scenario_HighM_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_HighN_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_HighO_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moWO","Scenario_HighP_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moW","Scenario_HighQ_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  ## Fast waning 
  load(here("Process_TDM_output","Output","9moWO","Scenario_HighB_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_HighC_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moWO","Scenario_HighD_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moW","Scenario_HighE_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_HighF_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_HighG_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_HighH_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_HighI_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_HighJ_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_HighK_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moWO","Scenario_HighL_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moW","Scenario_HighM_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_HighN_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_HighO_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moWO","Scenario_HighP_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moW","Scenario_HighQ_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  
  ## VERY HIGH INCIDENCE
  ## Slow waning 
  load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighB_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighC_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moWO","Scenario_VeryHighD_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moW","Scenario_VeryHighE_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighF_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighG_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighH_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighI_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighJ_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighK_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moWO","Scenario_VeryHighL_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moW","Scenario_VeryHighM_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighN_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighO_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moWO","Scenario_VeryHighP_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moW","Scenario_VeryHighQ_Slow_Doses_per_year.Rdata"), envir = .GlobalEnv)
  ## Fast waning 
  load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighB_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighC_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moWO","Scenario_VeryHighD_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moW","Scenario_VeryHighE_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighF_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighG_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighH_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighI_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighJ_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighK_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moWO","Scenario_VeryHighL_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moW","Scenario_VeryHighM_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moWO","Scenario_VeryHighN_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","9moW","Scenario_VeryHighO_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moWO","Scenario_VeryHighP_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
  load(here("Process_TDM_output","Output","15moW","Scenario_VeryHighQ_Fast_Doses_per_year.Rdata"), envir = .GlobalEnv)
}

